import { db, pool } from "./src/index.js";
import { cropAlertsTable, marketPricesTable, subsidiesTable } from "./src/schema/index.js";

async function seed() {
  console.log("Seeding MCP agricultural data...");

  await db.delete(cropAlertsTable);
  await db.delete(marketPricesTable);
  await db.delete(subsidiesTable);

  const now = new Date();
  const weekAgo = new Date(now.getTime() - 7 * 86400000);
  const monthAhead = new Date(now.getTime() + 30 * 86400000);
  const threeMonths = new Date(now.getTime() + 90 * 86400000);

  await db.insert(cropAlertsTable).values([
    { alertId: "ALT-IN-001", cropType: "rice", region: "Punjab", country: "India", threatType: "pest", threatName: "Brown Planthopper (BPH)", severity: "high", description: "Major BPH outbreak affecting basmati rice paddies. Insecticide resistance reported in Nilaparvata lugens populations.", advisoryText: "Apply imidacloprid 17.8 SL at 100ml/acre. Drain fields for 3 days. Avoid synthetic pyrethroids which cause BPH resurgence.", affectedAreaHa: 45000, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "ICAR-NRRI Advisory" },
    { alertId: "ALT-IN-002", cropType: "tomato", region: "Maharashtra", country: "India", threatType: "disease", threatName: "Tomato Leaf Curl Virus (ToLCV)", severity: "critical", description: "Whitefly-transmitted begomovirus causing severe leaf curling and stunting. Yield losses up to 100% in susceptible varieties.", advisoryText: "Remove and destroy infected plants. Install yellow sticky traps at 12/acre. Use neem oil 3000ppm spray every 7 days. Plant resistant varieties (Arka Rakshak, Arka Samrat).", affectedAreaHa: 12000, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "IIVR Varanasi" },
    { alertId: "ALT-IN-003", cropType: "wheat", region: "Uttar Pradesh", country: "India", threatType: "disease", threatName: "Yellow Rust (Puccinia striiformis)", severity: "medium", description: "Early-season yellow rust detected on susceptible varieties. Conditions favoring spread in irrigated tracts.", advisoryText: "Apply propiconazole 25 EC at 0.1% concentration. Monitor for fresh pustules weekly. Switch to resistant varieties HD-3226 or DBW-187 next season.", affectedAreaHa: 8500, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "ICAR-IIWBR" },
    { alertId: "ALT-PH-001", cropType: "rice", region: "Central Luzon", country: "Philippines", threatType: "pest", threatName: "Rice Black Bug (Scotinophara coarctata)", severity: "medium", description: "Rice black bug infestation during tillering stage. Deadheart symptoms observed in 15% of monitored fields.", advisoryText: "Apply fipronil 5 SC at 1.5L/ha or chlorpyrifos 20 EC. Maintain 5cm standing water. Use light traps at field edges.", affectedAreaHa: 5200, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "PhilRice" },
    { alertId: "ALT-TH-001", cropType: "rice", region: "Central Plains", country: "Thailand", threatType: "disease", threatName: "Rice Blast (Magnaporthe oryzae)", severity: "high", description: "Rice blast epidemic in glutinous rice varieties. Favorable weather conditions expected for next 2 weeks.", advisoryText: "Apply tricyclazole 75 WP at 0.6g/L preventively. Reduce nitrogen fertilizer application. Ensure adequate spacing between hills.", affectedAreaHa: 18000, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "Thai Rice Department" },
    { alertId: "ALT-VN-001", cropType: "coffee", region: "Central Highlands", country: "Vietnam", threatType: "disease", threatName: "Coffee Leaf Rust (Hemileia vastatrix)", severity: "high", description: "Coffee leaf rust spreading rapidly in robusta plantations. Defoliation exceeding 40% in some estates.", advisoryText: "Apply copper-based fungicide (Bordeaux mixture 1%) immediately. Prune lower branches for air circulation. Consider replanting with resistant clones TR4, TR9.", affectedAreaHa: 22000, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "WASI Vietnam" },
    { alertId: "ALT-BD-001", cropType: "rice", region: "Rangpur", country: "Bangladesh", threatType: "pest", threatName: "Stem Borer (Scirpophaga incertulas)", severity: "medium", description: "Yellow stem borer infestation in aman rice. Dead heart and white ear symptoms in 20% of surveyed fields.", advisoryText: "Release Trichogramma japonicum egg parasitoids at 1 lakh/ha. Install pheromone traps. Apply cartap hydrochloride 4G in leaf whorl.", affectedAreaHa: 9500, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "BRRI" },
    { alertId: "ALT-ID-001", cropType: "palm oil", region: "Sumatra", country: "Indonesia", threatType: "pest", threatName: "Rhinoceros Beetle (Oryctes rhinoceros)", severity: "medium", description: "Rhinoceros beetle damage in young palm oil plantations. V-shaped cuts on fronds with larval breeding in decomposing trunks.", advisoryText: "Apply Metarhizium anisopliae fungus to breeding sites. Install pheromone traps. Remove and shred old palm trunks to eliminate breeding habitat.", affectedAreaHa: 7800, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "IOPRI" },
    { alertId: "ALT-JP-001", cropType: "rice", region: "Niigata", country: "Japan", threatType: "disease", threatName: "Sheath Blight (Rhizoctonia solani)", severity: "low", description: "Minor sheath blight infection in Koshihikari rice. Limited to field margins near waterways.", advisoryText: "Apply validamycin A if infection exceeds 20% of tillers. Reduce planting density. Improve water management with intermittent irrigation.", affectedAreaHa: 1200, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "NARO Japan" },
    { alertId: "ALT-AU-001", cropType: "wheat", region: "New South Wales", country: "Australia", threatType: "disease", threatName: "Stripe Rust (Puccinia striiformis f. sp. tritici)", severity: "medium", description: "New pathotype detected in winter wheat. Early intervention recommended before flag leaf emergence.", advisoryText: "Apply tebuconazole + prothioconazole at 750ml/ha. Prioritize susceptible varieties. Consider fungicide seed treatment for next planting.", affectedAreaHa: 15000, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "CSIRO" },
    { alertId: "ALT-PK-001", cropType: "cotton", region: "Sindh", country: "Pakistan", threatType: "pest", threatName: "Pink Bollworm (Pectinophora gossypiella)", severity: "high", description: "Pink bollworm infestation in Bt cotton. Resistance to Cry1Ac protein confirmed in multiple districts.", advisoryText: "Implement refuge strategy (20% non-Bt cotton). Release Trichogramma wasps. Apply spinosad 45 SC at 75ml/acre targeting early bolls.", affectedAreaHa: 35000, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "PCCC Pakistan" },
    { alertId: "ALT-MY-001", cropType: "rice", region: "Kedah", country: "Malaysia", threatType: "pest", threatName: "Rice Leaf Folder (Cnaphalocrocis medinalis)", severity: "low", description: "Moderate leaf folder damage. Economic threshold not yet reached in most fields.", advisoryText: "Monitor damage levels. Apply chlorantraniliprole 18.5 SC if damage exceeds 2 damaged leaves per tiller. Encourage natural predators.", affectedAreaHa: 3000, reportedDate: weekAgo, expiresDate: monthAhead, isActive: true, source: "MARDI" },
  ]);

  await db.insert(marketPricesTable).values([
    { cropType: "rice", country: "India", market: "Karnal Mandi", pricePerKg: 22.5, currency: "INR", priceUsdPerKg: 0.27, weekOf: weekAgo, priceChange7d: 2.1, priceChange30d: 5.3, volume: "High", grade: "Grade A Basmati", source: "AgMarkNet" },
    { cropType: "rice", country: "India", market: "Cuttack APMC", pricePerKg: 18.0, currency: "INR", priceUsdPerKg: 0.22, weekOf: weekAgo, priceChange7d: -1.2, priceChange30d: 3.8, volume: "Medium", grade: "Common Paddy", source: "AgMarkNet" },
    { cropType: "wheat", country: "India", market: "Indore Mandi", pricePerKg: 25.5, currency: "INR", priceUsdPerKg: 0.31, weekOf: weekAgo, priceChange7d: 0.8, priceChange30d: -2.1, volume: "High", grade: "FAQ", source: "AgMarkNet" },
    { cropType: "tomato", country: "India", market: "Azadpur Delhi", pricePerKg: 35.0, currency: "INR", priceUsdPerKg: 0.42, weekOf: weekAgo, priceChange7d: 15.2, priceChange30d: 45.0, volume: "Medium", grade: "Hybrid", source: "AgMarkNet" },
    { cropType: "cotton", country: "India", market: "Rajkot APMC", pricePerKg: 62.0, currency: "INR", priceUsdPerKg: 0.74, weekOf: weekAgo, priceChange7d: -3.5, priceChange30d: -8.2, volume: "Low", grade: "S-6 (29mm)", source: "Cotton Association" },
    { cropType: "rice", country: "Thailand", market: "Bangkok FOB", pricePerKg: 18.5, currency: "THB", priceUsdPerKg: 0.54, weekOf: weekAgo, priceChange7d: 1.5, priceChange30d: 4.2, volume: "High", grade: "Thai Hom Mali 100%", source: "Thai Rice Exporters" },
    { cropType: "rice", country: "Philippines", market: "NFA Manila", pricePerKg: 45.0, currency: "PHP", priceUsdPerKg: 0.81, weekOf: weekAgo, priceChange7d: 0.5, priceChange30d: 2.1, volume: "Medium", grade: "Well-Milled", source: "PSA" },
    { cropType: "rice", country: "Vietnam", market: "HCMC Export", pricePerKg: 12500, currency: "VND", priceUsdPerKg: 0.50, weekOf: weekAgo, priceChange7d: 2.0, priceChange30d: 6.5, volume: "High", grade: "5% Broken", source: "VFA" },
    { cropType: "coffee", country: "Vietnam", market: "Dak Lak", pricePerKg: 95000, currency: "VND", priceUsdPerKg: 3.80, weekOf: weekAgo, priceChange7d: 5.2, priceChange30d: 12.8, volume: "High", grade: "Robusta Grade 1", source: "VICOFA" },
    { cropType: "palm oil", country: "Indonesia", market: "Medan FOB", pricePerKg: 12500, currency: "IDR", priceUsdPerKg: 0.79, weekOf: weekAgo, priceChange7d: -2.1, priceChange30d: -5.3, volume: "High", grade: "CPO", source: "GAPKI" },
    { cropType: "palm oil", country: "Malaysia", market: "Bursa Malaysia", pricePerKg: 3.85, currency: "MYR", priceUsdPerKg: 0.86, weekOf: weekAgo, priceChange7d: -1.8, priceChange30d: -4.2, volume: "High", grade: "CPO Futures", source: "MPOB" },
    { cropType: "wheat", country: "Australia", market: "APW Adelaide", pricePerKg: 0.38, currency: "AUD", priceUsdPerKg: 0.25, weekOf: weekAgo, priceChange7d: 1.2, priceChange30d: -3.5, volume: "Medium", grade: "APW", source: "AEGIC" },
    { cropType: "wheat", country: "Pakistan", market: "Lahore Commodity", pricePerKg: 70.0, currency: "PKR", priceUsdPerKg: 0.25, weekOf: weekAgo, priceChange7d: 0.3, priceChange30d: 1.5, volume: "High", grade: "FAQ", source: "PMEX" },
    { cropType: "rice", country: "Bangladesh", market: "Dhaka Wholesale", pricePerKg: 55.0, currency: "BDT", priceUsdPerKg: 0.50, weekOf: weekAgo, priceChange7d: 3.0, priceChange30d: 8.5, volume: "High", grade: "BRRI-28 Aman", source: "DAM" },
    { cropType: "rice", country: "Japan", market: "Tokyo Wholesale", pricePerKg: 420, currency: "JPY", priceUsdPerKg: 2.80, weekOf: weekAgo, priceChange7d: 0.2, priceChange30d: 0.8, volume: "Low", grade: "Koshihikari", source: "MAFF" },
    { cropType: "cotton", country: "Pakistan", market: "Karachi Spot", pricePerKg: 290, currency: "PKR", priceUsdPerKg: 1.04, weekOf: weekAgo, priceChange7d: -4.2, priceChange30d: -10.5, volume: "Medium", grade: "AFZAL (29mm)", source: "KCA" },
    { cropType: "sugarcane", country: "India", market: "Kolhapur", pricePerKg: 3.15, currency: "INR", priceUsdPerKg: 0.038, weekOf: weekAgo, priceChange7d: 0.0, priceChange30d: 0.0, volume: "High", grade: "FRP", source: "CACP", notes: "Fair and Remunerative Price" },
    { cropType: "rubber", country: "Thailand", market: "Hat Yai", pricePerKg: 65.0, currency: "THB", priceUsdPerKg: 1.90, weekOf: weekAgo, priceChange7d: 3.8, priceChange30d: 9.2, volume: "Medium", grade: "RSS3", source: "RAOT" },
    { cropType: "tea", country: "India", market: "Guwahati Auction", pricePerKg: 245, currency: "INR", priceUsdPerKg: 2.95, weekOf: weekAgo, priceChange7d: -1.5, priceChange30d: -4.2, volume: "Medium", grade: "CTC BOP", source: "Tea Board India" },
    { cropType: "coconut", country: "Philippines", market: "Manila Copra", pricePerKg: 52.0, currency: "PHP", priceUsdPerKg: 0.94, weekOf: weekAgo, priceChange7d: 2.5, priceChange30d: 7.8, volume: "High", grade: "Copra Resecada", source: "PCA" },
  ]);

  await db.insert(subsidiesTable).values([
    { programId: "SUB-IN-001", programName: "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)", country: "India", administeredBy: "Ministry of Agriculture, Government of India", description: "Direct income support of INR 6000/year to smallholder farmer families in three installments.", eligibleCrops: "all", eligibilityCriteria: "Landholding farmer families with cultivable land. Excludes institutional landholders, income tax payers, and government employees.", benefitType: "direct_cash_transfer", maxBenefitUsd: 72, applicationDeadline: threeMonths, applicationUrl: "https://pmkisan.gov.in", isActive: true, targetRegion: "All India", minFarmSizeHa: 0, maxFarmSizeHa: null, lastUpdated: now },
    { programId: "SUB-IN-002", programName: "Pradhan Mantri Fasal Bima Yojana (PMFBY)", country: "India", administeredBy: "Ministry of Agriculture, Government of India", description: "Crop insurance scheme with farmer premium of 2% for kharif crops, 1.5% for rabi crops, and 5% for commercial/horticultural crops.", eligibleCrops: "rice,wheat,cotton,sugarcane,pulses,oilseeds,vegetables", eligibilityCriteria: "All farmers including sharecroppers and tenant farmers growing notified crops. Voluntary for non-loanee farmers.", benefitType: "insurance_premium_subsidy", maxBenefitUsd: null, applicationDeadline: monthAhead, applicationUrl: "https://pmfby.gov.in", isActive: true, targetRegion: "All India", lastUpdated: now },
    { programId: "SUB-IN-003", programName: "Soil Health Card Scheme", country: "India", administeredBy: "Department of Agriculture & Farmers' Welfare", description: "Free soil testing and nutrient management recommendations. Includes subsidized micro-nutrients and bio-fertilizers.", eligibleCrops: "all", eligibilityCriteria: "Any farmer with cultivable land. Priority to farmers who have not received a soil health card in the last 2 years.", benefitType: "in_kind_service", maxBenefitUsd: 25, isActive: true, targetRegion: "All India", lastUpdated: now },
    { programId: "SUB-TH-001", programName: "Rice Income Guarantee Scheme", country: "Thailand", administeredBy: "Ministry of Commerce, Thailand", description: "Price guarantee for rice farmers. Government pays the difference between market price and guaranteed price of 10,000 THB/tonne for white rice.", eligibleCrops: "rice", eligibilityCriteria: "Registered rice farmers with maximum 40 rai (6.4 ha) of paddy land. Must register with Bank for Agriculture and Agricultural Cooperatives (BAAC).", benefitType: "price_guarantee", maxBenefitUsd: 860, applicationDeadline: threeMonths, isActive: true, targetRegion: "All Thailand", maxFarmSizeHa: 6.4, lastUpdated: now },
    { programId: "SUB-PH-001", programName: "Rice Competitiveness Enhancement Fund (RCEF)", country: "Philippines", administeredBy: "Department of Agriculture, Philippines", description: "10 billion PHP annual fund providing free certified seeds, farm machinery, credit, and extension services to rice farmers.", eligibleCrops: "rice", eligibilityCriteria: "Small rice farmers with 0.5-5 hectares registered in the RSBSA (Registry System for Basic Sectors in Agriculture).", benefitType: "in_kind_seeds_machinery", maxBenefitUsd: 500, isActive: true, targetRegion: "All Philippines", minFarmSizeHa: 0.5, maxFarmSizeHa: 5, lastUpdated: now },
    { programId: "SUB-VN-001", programName: "Coffee Replanting Support Program", country: "Vietnam", administeredBy: "Ministry of Agriculture and Rural Development, Vietnam", description: "Low-interest loans and seedling subsidies for replanting aging coffee plantations with high-yield, disease-resistant varieties.", eligibleCrops: "coffee", eligibilityCriteria: "Coffee farmers in Central Highlands provinces (Dak Lak, Lam Dong, Gia Lai, Dak Nong, Kon Tum) with coffee trees older than 20 years.", benefitType: "subsidized_loan_and_seedlings", maxBenefitUsd: 2500, isActive: true, targetRegion: "Central Highlands", lastUpdated: now },
    { programId: "SUB-BD-001", programName: "Agriculture Input Subsidy Card", country: "Bangladesh", administeredBy: "Ministry of Agriculture, Bangladesh", description: "Subsidized fertilizers, seeds, and diesel fuel for irrigation. Urea subsidy of 50%, TSP 30%, MoP 20%.", eligibleCrops: "rice,wheat,vegetables,pulses", eligibilityCriteria: "Smallholder farmers with less than 2.5 acres (1 ha) of cultivable land. Must have agriculture input subsidy card issued by Upazila Agriculture Office.", benefitType: "input_subsidy", maxBenefitUsd: 150, isActive: true, targetRegion: "All Bangladesh", maxFarmSizeHa: 1, lastUpdated: now },
    { programId: "SUB-ID-001", programName: "Pupuk Bersubsidi (Subsidized Fertilizer)", country: "Indonesia", administeredBy: "Ministry of Agriculture, Indonesia", description: "Government-subsidized urea and NPK fertilizer at fixed prices for smallholder food crop farmers.", eligibleCrops: "rice,corn,soybean,sugarcane", eligibilityCriteria: "Farmers registered in RDKK (Definitive Plan for Group Needs) with maximum 2 hectares of food crop land.", benefitType: "input_subsidy", maxBenefitUsd: 200, isActive: true, targetRegion: "All Indonesia", maxFarmSizeHa: 2, lastUpdated: now },
    { programId: "SUB-PK-001", programName: "Kisan Card (Prime Minister's Agriculture Emergency Programme)", country: "Pakistan", administeredBy: "Ministry of National Food Security, Pakistan", description: "Interest-free loans up to PKR 150,000 for crop inputs, plus subsidized seeds and fertilizers.", eligibleCrops: "wheat,cotton,rice,sugarcane", eligibilityCriteria: "Small farmers with landholding up to 12.5 acres (5 ha). Must have valid CNIC and land ownership documents.", benefitType: "interest_free_loan", maxBenefitUsd: 540, isActive: true, targetRegion: "All Pakistan", maxFarmSizeHa: 5, lastUpdated: now },
    { programId: "SUB-AU-001", programName: "Farm Household Allowance", country: "Australia", administeredBy: "Services Australia", description: "Income support payments for eligible farmers experiencing financial hardship, including activity supplements for upskilling.", eligibleCrops: "all", eligibilityCriteria: "Farmers who have been farming for at least 2 years and meet income and assets tests. Farm enterprise must have produced gross farm revenue.", benefitType: "direct_cash_transfer", maxBenefitUsd: 12000, applicationUrl: "https://www.servicesaustralia.gov.au/farm-household-allowance", isActive: true, targetRegion: "All Australia", lastUpdated: now },
    { programId: "SUB-JP-001", programName: "Income Insurance for Farmers", country: "Japan", administeredBy: "Ministry of Agriculture, Forestry and Fisheries (MAFF)", description: "Revenue insurance covering up to 90% of income shortfall when farm income falls below the average of the past 5 years.", eligibleCrops: "all", eligibilityCriteria: "Farmers who have filed blue tax returns for at least 1 year. Must not be enrolled in other agricultural mutual aid schemes.", benefitType: "insurance", maxBenefitUsd: 30000, isActive: true, targetRegion: "All Japan", lastUpdated: now },
    { programId: "SUB-MY-001", programName: "Skim Subsidi Padi (Paddy Subsidy Scheme)", country: "Malaysia", administeredBy: "Ministry of Agriculture and Food Security, Malaysia", description: "Price subsidy of RM 360/tonne of paddy plus monthly allowance of RM 200 for registered paddy farmers.", eligibleCrops: "rice", eligibilityCriteria: "Paddy farmers registered with Pertubuhan Peladang (Farmers' Organization) or IADA. Must cultivate at least 1 relong (0.27 ha) of paddy.", benefitType: "price_subsidy_and_allowance", maxBenefitUsd: 1000, isActive: true, targetRegion: "All Malaysia", minFarmSizeHa: 0.27, lastUpdated: now },
  ]);

  console.log("Seeded 12 crop alerts, 20 market prices, 12 subsidies across 10 APAC countries.");
  await pool.end();
}

seed().catch((e) => { console.error(e); process.exit(1); });
